#!/usr/bin/env bash
# Link the team skills into whichever assistants you use.
# Skills stay in this repo; these are symlinks, so `git pull` updates them.
#
#   ./scripts/install.sh gemini   -> .gemini/skills/      (this workspace)
#   ./scripts/install.sh codex    -> ~/.codex/skills/     (all projects)
#   ./scripts/install.sh claude   -> prints the plugin command
#   ./scripts/install.sh all
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

# $1 = target dir, $2 = human label, $3 = "relative" to make in-repo links
# portable (so they survive a fresh clone), otherwise absolute.
link_all() {
  mkdir -p "$1"
  local n=0 target
  for d in "$ROOT"/categories/*/skills/*/; do
    d="${d%/}"
    if [ "${3:-}" = "relative" ]; then
      target="../../${d#"$ROOT"/}"
    else
      target="$d"
    fi
    ln -sfn "$target" "$1/$(basename "$d")"
    n=$((n+1))
  done
  echo "  linked $n skills into $2"
}

do_gemini() {
  echo "Gemini CLI:"
  link_all "$ROOT/.gemini/skills" ".gemini/skills/ (workspace)" relative
  echo "  note: skills are experimental — .gemini/settings.json enables them"
  echo "  also available as slash commands: /<category>:<skill>"
}

do_codex() {
  echo "Codex:"
  if [ -d "$HOME/.codex" ]; then
    link_all "$HOME/.codex/skills" "~/.codex/skills/ (Codex app, all projects)"
  else
    echo "  ~/.codex not found — skipping app skills"
  fi
  echo "  Codex CLI reads AGENTS.md at the repo root (generated by build.py)"
}

do_claude() {
  echo "Claude Code — install the categories you want:"
  echo "  claude plugin marketplace add $ROOT"
  echo "  claude plugin install team-engineering@team-ai-skills"
}

case "${1:-all}" in
  gemini) do_gemini ;;
  codex)  do_codex ;;
  claude) do_claude ;;
  all)    do_gemini; echo; do_codex; echo; do_claude ;;
  *) echo "usage: $0 [gemini|codex|claude|all]" >&2; exit 1 ;;
esac
